# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogout1():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://blibli.com', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogout1(self):
    self.driver.get("https://www.blibli.com/")
    self.driver.set_window_size(1440, 804)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn__login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn__login").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "bli-input-cvwxj483t").send_keys("rosalindaa33333@gmail.com")
    self.driver.find_element(By.ID, "bli-input-nrwormfnr7").click()
    self.driver.find_element(By.ID, "bli-input-nrwormfnr7").send_keys("Rosalinda123")
    self.driver.find_element(By.ID, "bli-input-nrwormfnr7").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".wrapper-logout__item").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".favourite__item:nth-child(12) img")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
