# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestregistrasi2:
    def setup_method(self, method):
        self.driver = webdriver.Remote(
            command_executor="http://blibli.com",
            desired_capabilities=DesiredCapabilities.CHROME,
        )
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testregistrasi2(self):
        self.driver.get("https://www.blibli.com/")
        self.driver.set_window_size(1440, 804)
        element = self.driver.find_element(By.CSS_SELECTOR, ".btn__register")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".btn__register").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.ID, "bli-input-7vltb9i7f").click()
        self.driver.find_element(By.ID, "bli-input-7vltb9i7f").send_keys("rosalinda")
        self.driver.find_element(By.ID, "bli-input-s314oryxh").click()
        self.driver.find_element(By.ID, "bli-input-s314oryxh").send_keys(
            "rosalinda3333@gmail.com"
        )
        self.driver.find_element(By.ID, "bli-input-7wtbg9atr").click()
        self.driver.find_element(By.ID, "bli-input-7wtbg9atr").click()
        self.driver.find_element(By.ID, "bli-input-7wtbg9atr").click()
        self.driver.find_element(By.ID, "bli-input-7wtbg9atr").send_keys("asdsadasdas")
        self.driver.find_element(By.CSS_SELECTOR, "button > svg").click()
        self.driver.find_element(By.CSS_SELECTOR, ".blu-checkbox > label").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".b-full-width")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".b-full-width").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
