# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestgantisandi():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://blibli.com', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testgantisandi(self):
    self.driver.get("https://www.blibli.com/")
    self.driver.set_window_size(1440, 804)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn__register")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn__register")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn__login").click()
    self.driver.find_element(By.ID, "bli-input-oz6ljsie").send_keys("rosalindaa33333@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".login__password-container > label").click()
    self.driver.find_element(By.ID, "bli-input-2d2e1mr1j").send_keys("Rosalinda123")
    element = self.driver.find_element(By.CSS_SELECTOR, ".b-full-width")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".b-full-width").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".favourite__item:nth-child(12) > .favourite__item-image")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bell-notification path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "moe-onsite-campaign-65646cffbb27647a72d6cf18").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".brz-icon-svg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".brz-icon-svg").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".blu-ticker__close > i").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text__link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tabs__header-title:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".blu-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "a > .blu-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "a > .blu-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".password-page__input:nth-child(4) label").click()
    self.driver.find_element(By.ID, "bli-input-s5zp3eg3e").send_keys("Rosalinda123")
    self.driver.find_element(By.CSS_SELECTOR, ".has-value svg").click()
    self.driver.find_element(By.ID, "bli-input-xlbiacw2s").click()
    self.driver.find_element(By.ID, "bli-input-xlbiacw2s").click()
    self.driver.find_element(By.ID, "bli-input-xlbiacw2s").send_keys("Rosalinda12345")
    self.driver.find_element(By.CSS_SELECTOR, ".password-page__input:nth-child(5) svg").click()
    self.driver.find_element(By.CSS_SELECTOR, "#main-ui-wrapper > span").click()
    self.driver.find_element(By.ID, "bli-input-tnbiilq2s").click()
    self.driver.find_element(By.ID, "bli-input-tnbiilq2s").send_keys("Rosalinda12345")
    self.driver.find_element(By.CSS_SELECTOR, ".password-page__input:nth-child(6) path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".blu-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active").send_keys("8")
    self.driver.find_element(By.CSS_SELECTOR, ".active").send_keys("9")
  
