# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestregistrasi3():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://blibli.com', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testregistrasi3(self):
    self.driver.get("https://www.blibli.com/")
    self.driver.set_window_size(1440, 804)
    self.driver.find_element(By.CSS_SELECTOR, ".btn__register").click()
    self.driver.find_element(By.ID, "bli-input-a5y69xyf").click()
    self.driver.find_element(By.ID, "bli-input-a5y69xyf").send_keys("Rosalinda")
    self.driver.find_element(By.ID, "bli-input-6gwr44rgu").click()
    self.driver.find_element(By.ID, "bli-input-6gwr44rgu").send_keys("rosalinda3333@gmail.com")
    self.driver.find_element(By.ID, "bli-input-vfkoisjxl").click()
    self.driver.find_element(By.ID, "bli-input-vfkoisjxl").click()
    self.driver.find_element(By.ID, "bli-input-vfkoisjxl").send_keys("Rosalinda123")
    self.driver.find_element(By.CSS_SELECTOR, ".register-page__form").click()
    self.driver.find_element(By.ID, "bli-input-vfkoisjxl").click()
    self.driver.find_element(By.ID, "bli-input-vfkoisjxl").click()
    self.driver.find_element(By.CSS_SELECTOR, "button > svg > path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".blu-checkbox > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".b-full-width").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".b-full-width")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".b-full-width")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
