# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestlogin1():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://blibli.com', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testlogin1(self):
    self.driver.get("https://www.blibli.com/")
    self.driver.set_window_size(1440, 804)
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn__register")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn__login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn__login").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "bli-input-9eidsudt").send_keys("rosalindaa33333@gmail.com")
    self.driver.find_element(By.ID, "bli-input-38v0nmwzu").send_keys("Rosalinda123")
    element = self.driver.find_element(By.CSS_SELECTOR, ".b-full-width")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".b-full-width").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".b-full-width")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".otp-type-selection__send > .blu-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active").send_keys("9")
    self.driver.find_element(By.CSS_SELECTOR, ".active").send_keys("7")
    self.driver.find_element(By.CSS_SELECTOR, ".active").send_keys("5")
    self.driver.find_element(By.CSS_SELECTOR, ".active").send_keys("6")
    self.driver.find_element(By.CSS_SELECTOR, ".blu-ticker__close > i").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bell-notification .icon-gray")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".account__icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".account__text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
